/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFloorReviewRouteImport } from './routes/_authenticated/floor-review'
import { Route as AuthenticatedFormBuilderRouteImport } from './routes/_authenticated/form-builder'
import { Route as AuthenticatedMasterDataRouteImport } from './routes/_authenticated/master-data'
import { Route as AuthenticatedMyRequestsRouteImport } from './routes/_authenticated/my-requests'
import { Route as AuthenticatedNewDeviationRouteImport } from './routes/_authenticated/new-deviation'
import { Route as AuthenticatedPpcReviewRouteImport } from './routes/_authenticated/ppc-review'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFloorReviewRoute =
  AuthenticatedFloorReviewRouteImport.update({
    id: '/floor-review',
    path: '/floor-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormBuilderRoute =
  AuthenticatedFormBuilderRouteImport.update({
    id: '/form-builder',
    path: '/form-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterDataRoute = AuthenticatedMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRequestsRoute = AuthenticatedMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewDeviationRoute =
  AuthenticatedNewDeviationRouteImport.update({
    id: '/new-deviation',
    path: '/new-deviation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPpcReviewRoute = AuthenticatedPpcReviewRouteImport.update({
  id: '/ppc-review',
  path: '/ppc-review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/floor-review': typeof AuthenticatedFloorReviewRoute
  '/form-builder': typeof AuthenticatedFormBuilderRoute
  '/master-data': typeof AuthenticatedMasterDataRoute
  '/my-requests': typeof AuthenticatedMyRequestsRoute
  '/new-deviation': typeof AuthenticatedNewDeviationRoute
  '/ppc-review': typeof AuthenticatedPpcReviewRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/floor-review': typeof AuthenticatedFloorReviewRoute
  '/form-builder': typeof AuthenticatedFormBuilderRoute
  '/master-data': typeof AuthenticatedMasterDataRoute
  '/my-requests': typeof AuthenticatedMyRequestsRoute
  '/new-deviation': typeof AuthenticatedNewDeviationRoute
  '/ppc-review': typeof AuthenticatedPpcReviewRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/floor-review': typeof AuthenticatedFloorReviewRoute
  '/_authenticated/form-builder': typeof AuthenticatedFormBuilderRoute
  '/_authenticated/master-data': typeof AuthenticatedMasterDataRoute
  '/_authenticated/my-requests': typeof AuthenticatedMyRequestsRoute
  '/_authenticated/new-deviation': typeof AuthenticatedNewDeviationRoute
  '/_authenticated/ppc-review': typeof AuthenticatedPpcReviewRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit-log'
    | '/dashboard'
    | '/floor-review'
    | '/form-builder'
    | '/master-data'
    | '/my-requests'
    | '/new-deviation'
    | '/ppc-review'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audit-log'
    | '/dashboard'
    | '/floor-review'
    | '/form-builder'
    | '/master-data'
    | '/my-requests'
    | '/new-deviation'
    | '/ppc-review'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit-log'
    | '/_authenticated/dashboard'
    | '/_authenticated/floor-review'
    | '/_authenticated/form-builder'
    | '/_authenticated/master-data'
    | '/_authenticated/my-requests'
    | '/_authenticated/new-deviation'
    | '/_authenticated/ppc-review'
    | '/_authenticated/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/floor-review': {
      id: '/_authenticated/floor-review'
      path: '/floor-review'
      fullPath: '/floor-review'
      preLoaderRoute: typeof AuthenticatedFloorReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/form-builder': {
      id: '/_authenticated/form-builder'
      path: '/form-builder'
      fullPath: '/form-builder'
      preLoaderRoute: typeof AuthenticatedFormBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-data': {
      id: '/_authenticated/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof AuthenticatedMasterDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-requests': {
      id: '/_authenticated/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof AuthenticatedMyRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-deviation': {
      id: '/_authenticated/new-deviation'
      path: '/new-deviation'
      fullPath: '/new-deviation'
      preLoaderRoute: typeof AuthenticatedNewDeviationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ppc-review': {
      id: '/_authenticated/ppc-review'
      path: '/ppc-review'
      fullPath: '/ppc-review'
      preLoaderRoute: typeof AuthenticatedPpcReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFloorReviewRoute: typeof AuthenticatedFloorReviewRoute
  AuthenticatedFormBuilderRoute: typeof AuthenticatedFormBuilderRoute
  AuthenticatedMasterDataRoute: typeof AuthenticatedMasterDataRoute
  AuthenticatedMyRequestsRoute: typeof AuthenticatedMyRequestsRoute
  AuthenticatedNewDeviationRoute: typeof AuthenticatedNewDeviationRoute
  AuthenticatedPpcReviewRoute: typeof AuthenticatedPpcReviewRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFloorReviewRoute: AuthenticatedFloorReviewRoute,
  AuthenticatedFormBuilderRoute: AuthenticatedFormBuilderRoute,
  AuthenticatedMasterDataRoute: AuthenticatedMasterDataRoute,
  AuthenticatedMyRequestsRoute: AuthenticatedMyRequestsRoute,
  AuthenticatedNewDeviationRoute: AuthenticatedNewDeviationRoute,
  AuthenticatedPpcReviewRoute: AuthenticatedPpcReviewRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
